server:
  port: 8084

spring:
  application:
    name: report-generator
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/planny?authSource=admin
      database: "mongodb"

services:
  db-planny-service: ${SERVICES_DB_PLANNY_SERVICE}

logging:
  file:
    name: /data/logs/log_report-generator
