server:
  port: 8081

spring:
  application:
    name: db-planny-service
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 6
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: off
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

logging:
  file:
    name: /data/logs/log_db-planny-service
