server:
  port: 8085

spring:
  application:
    name: editor-planny-ui
  thymeleaf:
    cache: true

services:
  db-planny-service: ${SERVICES_DB_PLANNY_SERVICE}

logging:
  file:
    name: /data/logs/log_editor-planny-ui
