server:
  port: 8085

spring:
  application:
    name: editor-planny-ui
  thymeleaf:
    cache: true

services:
  db-planny-service: ${services.db-planny-service}

logging:
  file:
    name: logs/log_editor-planny-ui
