server:
  port: 8086

spring:
  application:
    name: db-user-PA-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/planny?authSource=admin
      database: "mongo_planny"

jwt:
  secret: ${JWT_SECRET}

logging:
  file:
    name: /data/logs/log_db-user-PA-service