server:
  port: 8083

spring:
  application:
    name: tg-bot-planny
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/planny?authSource=admin
      database: "mongodb"

services:
  report-generator: ${SERVICES_REPORT_GENERATOR}
  editor-planny-ui: ${SERVICES_EDITOR_PLANNY_UI}

telegrambot:
  name: ${TELEGRAMBOT_NAME}
  id: ${TELEGRAMBOT_ID}
  token: ${TELEGRAMBOT_TOKEN}

jwt:
  secret: ${JWT_SECRET}

logging:
  file:
    name: /data/logs/log_tg-bot-planny