server:
  port: 8083

spring:
  application:
    name: tg-bot-planny
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: "mongodb"

services:
  report-generator: ${services.report-generator}
  editor-planny-ui: ${services.editor-planny-ui}

telegrambot:
  name: ${TELEGRAMBOT_NAME}
  id: ${TELEGRAMBOT_ID}
  token: ${TELEGRAMBOT_TOKEN}

jwt:
  secret: ${JWT_SECRET}

logging:
  file:
    name: logs/log_tg-bot-planny